#
# Copyright (c) 2017, 2020 ADLINK Technology Inc.
#
# This program and the accompanying materials are made available under the
# terms of the Eclipse Public License 2.0 which is available at
# http://www.eclipse.org/legal/epl-2.0, or the Apache License, Version 2.0
# which is available at https://www.apache.org/licenses/LICENSE-2.0.
#
# SPDX-License-Identifier: EPL-2.0 OR Apache-2.0
#
# Contributors:
#   ADLINK zenoh team, <zenoh@adlink-labs.tech>
#
name: Rust

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Install APT pre-requisites
      run: sudo apt-get update && sudo apt-get -y install curl gnupg2 lsb-release
    
    - name: Install Cyclone DDS
      run: |
        mkdir -p ${{runner.workspace}}/work
        cd ${{runner.workspace}}/work
        git clone --depth 1 -b 0.7.0 https://github.com/eclipse-cyclonedds/cyclonedds.git
        cd cyclonedds
        mkdir -p build
        cd build
        cmake ..
        sudo cmake --build . --target install

    - name: Install CycloCut
      run: |
        mkdir -p ${{runner.workspace}}/work
        cd ${{runner.workspace}}/work
        git clone https://github.com/kydos/cyclocut.git
        cd cyclocut
        mkdir -p build
        cd build
        cmake ..
        sudo cmake --build . --target install

    - uses: actions/checkout@v2

    - name: Install Rust
      uses: actions-rs/toolchain@v1
      with:
          components: rustfmt, clippy


    - name: Run cargo check
      uses: actions-rs/cargo@v1
      with:
        command: check

    - name: Build
      uses: actions-rs/cargo@v1
      with:
        command: build
        args: --verbose --all-targets

    - name: Clippy
      uses: actions-rs/cargo@v1
      with:
        command: clippy
        args: --all --examples

    - name: Run tests
      uses: actions-rs/cargo@v1
      with:
        command: test
        args: --verbose

    - name: Run rustfmt
      uses: actions-rs/cargo@v1
      with:
        command: fmt
        args: -- --check
